' Hidden launcher for Task Scheduler — no console window.
' Generated by htoc_ml.tools.make_launcher. Path is relative to this .vbs.
Option Explicit
Dim sh, fso, folder, bat, rc, cmd
Set sh = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")
folder = fso.GetParentFolderName(WScript.ScriptFullName)
bat = folder & "\run_prism_daily.bat"
cmd = "cmd.exe /c call """ & bat & """"
rc = sh.Run(cmd, 0, True)
If rc < 0 Then
  rc = 1
End If
WScript.Quit rc
