@echo off
setlocal EnableExtensions EnableDelayedExpansion
REM ============================================================================
REM PRISM indicator triage
REM Generated by htoc.datapipelines.make_launcher. Task Scheduler should call the
REM sibling _hidden.vbs, not this file directly.
REM Regenerate: py -3.13 -m htoc.datapipelines make-launcher --name triage
REM ============================================================================

if not exist "C:\Temp" mkdir "C:\Temp" >nul 2>&1
echo [%date% %time%] bat started from: %~dp0 > "C:\Temp\triage_debug.txt" 2>&1

if not defined HTOC_SHARE_ROOT set "HTOC_SHARE_ROOT=\\cscso1fsappv01\data\HTOC"

if not defined PYTHON_EXE (
    py -3.13 --version >nul 2>&1
    if "!ERRORLEVEL!"=="0" (
        for /f "delims=" %%p in ('py -3.13 -c "import sys; print(sys.executable)"') do set "PYTHON_EXE=%%p"
    ) else (
        set "PYTHON_EXE=%HTOC_SHARE_ROOT%\JA\Python313\python.exe"
    )
)

set "HTOC_ML_ROOT=%~dp0..\..\..\.."
set "LOG_DIR=%~dp0logs\triage"
set "SUCCESS_MARKER=PIPELINE_OK"
set "PYTHONPATH=%HTOC_ML_ROOT%\src;%PYTHONPATH%"

if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"
forfiles /p "%LOG_DIR%" /m "*.log" /d -14 /c "cmd /c del /q @path" >nul 2>&1

for /f %%i in ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd"') do set "TODAY_STR=%%i"
set "_TS_RAW=%TIME: =0%"
set "NOW_STR=%_TS_RAW:~0,2%%_TS_RAW:~3,2%%_TS_RAW:~6,2%"
set "TS=%TODAY_STR%_%NOW_STR%"
set "LOG_FILE=%LOG_DIR%\triage_%TS%.log"
set "TEMP_OUT=%LOG_DIR%\temp_output_%TS%.log"

call :log START   PRISM indicator triage
call :log CONFIG  Python: %PYTHON_EXE%
call :log CONFIG  Module: -m htoc.datapipelines triage
call :log CONFIG  Root:   %HTOC_ML_ROOT%
call :log CONFIG  Log:    %LOG_FILE%
call :log RUN     Connecting data share...
call "%~dp0ensure_htoc_data_share.bat" >> "%LOG_FILE%" 2>&1
if errorlevel 1 (
    call :log ERROR   Cannot reach HTOC data share %HTOC_SHARE_ROOT%
    exit /b 3
)
call :log CHECK   Data share OK (%HTOC_SHARE_ROOT%)

if not exist "%PYTHON_EXE%" (
    call :log ERROR   Python not found: %PYTHON_EXE%
    exit /b 1
)

set "PYTHONUSERBASE=%USERPROFILE%\AppData\Roaming\Python"
set "PYTHONIOENCODING=utf-8"
set "PYTHONUTF8=1"
set "TMP=C:\Temp"
set "TEMP=C:\Temp"
if not exist "%TMP%" mkdir "%TMP%" >nul 2>&1

pushd "%HTOC_ML_ROOT%" >nul 2>&1
if errorlevel 1 (
    call :log ERROR   Failed to pushd HTOC_ML_ROOT
    exit /b 1
)

set "PKGS=pandas openpyxl requests"
set "PIP_FLAGS=--user --disable-pip-version-check --no-warn-script-location --no-cache-dir --timeout 120 --retries 10"
set "PIP_TRUST=--trusted-host pypi.org --trusted-host files.pythonhosted.org --trusted-host pypi.python.org"
set "PIP_OK=0"
set "WHEELHOUSE=%HTOC_SHARE_ROOT%\JA\wheelhouse"
call :log RUN     Installing packages...
if exist "%WHEELHOUSE%" (
    "%PYTHON_EXE%" -m pip install --user --no-index --find-links="%WHEELHOUSE%" %PKGS% > "%TEMP_OUT%" 2>&1
    if "!ERRORLEVEL!"=="0" set "PIP_OK=1"
)
if "!PIP_OK!"=="0" (
    "%PYTHON_EXE%" -m pip install %PIP_FLAGS% %PIP_TRUST% %PKGS% > "%TEMP_OUT%" 2>&1
    if "!ERRORLEVEL!"=="0" set "PIP_OK=1"
)
type "%TEMP_OUT%" >> "%LOG_FILE%" 2>nul
if not "!PIP_OK!"=="1" (
    call :log ERROR   Package install failed
    popd >nul
    exit /b 1
)
call :log CHECK   Packages OK

call :log RUN     Launching -m htoc.datapipelines triage...
"%PYTHON_EXE%" -u -m htoc.datapipelines triage > "%TEMP_OUT%" 2>&1
set "SCRIPT_EXIT_CODE=!ERRORLEVEL!"
popd >nul 2>&1

if not defined SCRIPT_EXIT_CODE set "SCRIPT_EXIT_CODE=1"
call :log RUN     Script exited with code !SCRIPT_EXIT_CODE!

echo. >> "%LOG_FILE%"
echo ---- script output ---- >> "%LOG_FILE%"
type "%TEMP_OUT%" >> "%LOG_FILE%" 2>nul
echo ---- end output ---- >> "%LOG_FILE%"
echo. >> "%LOG_FILE%"

set "FINAL_EXIT=1"
if not "!SCRIPT_EXIT_CODE!"=="0" (
    call :log ERROR   Script failed with exit code !SCRIPT_EXIT_CODE!
    goto :finish
)

call :log SUCCESS Completed successfully (exit 0; no PIPELINE_OK required)
set "FINAL_EXIT=0"

:finish
if exist "%TEMP_OUT%" del "%TEMP_OUT%" >nul 2>&1
call :log END     Batch complete with exit !FINAL_EXIT!
exit /b !FINAL_EXIT!

:log
set "_T=%TIME: =0%"
echo [%TODAY_STR% %_T:~0,8%] %*
echo [%TODAY_STR% %_T:~0,8%] %*>> "%LOG_FILE%" 2>nul
exit /b 0
